# config.yaml

# Google API scopes needed for Gmail and Calendar access
SCOPES:
  - https://www.googleapis.com/auth/gmail.readonly
  - https://www.googleapis.com/auth/gmail.send
  - https://www.googleapis.com/auth/calendar

# Paths for OAuth credentials
CREDENTIALS_FILE: "credentials.json"
TOKEN_FILE: "token.json"

# OpenAI key
OPENAI_API_KEY: "${OPENAI_API_KEY}"

# Time zone
LOCAL_TIMEZONE: "America/New_York"

# Optional: any other custom settings
CALENDAR_ID: "primary"
CHECK_EMAIL_FREQUENCY_SECONDS: 30
